export const invitation = {
  firstName: "Shubh",
  secondName: "Suchita",
  names: "Shubh & Suchita",
  invitation: "With our families by our side, we'd love to have you with us as we begin our forever.",
  dates: "25 & 26 January 2027",
  dateNumerals: "25 . 26 . 01 . 2027",
  venue: "Evara Spa & Resort",
  destination: "Jim Corbett, Uttarakhand, India",
  address: "Village Bhalon, Patkot, Uttarakhand 263159",
  venueUrl: "https://www.evararesort.com/",
  venueGalleryUrl: "https://www.evararesort.com/gallery.html",
  venueDescription: "Meet us among the green hills of Jim Corbett. We've saved two days for laughter, dancing, long conversations and the joy of having everyone together.",
  directionsUrl: "https://www.evararesort.com/location.html",
  calendarStart: "20270125",
  calendarEndExclusive: "20270127",
  calendarUid: "shubh-suchita-wedding-20270125",
  countdownTarget: "2027-01-25T12:00:00+05:30",
  scheduleNote: "All celebration times are in Indian Standard Time (IST).",
  guestNote: "Travel and stay details are forthcoming.",
  note: "As we get ready to say yes to a lifetime together, we're thinking of the people we want around us. You are one of them. Come share the happy chaos, the quiet moments and all the love these two days will hold. Having you there would mean so much to us.",
  closing: "It won't be the same without you.",
  artwork: "assets/artwork/couple-transparent.png",
  artworkAlt: "Shubh and Suchita's pink illustrated wedding artwork with florals, two dogs, a teacup and a city bridge.",
  entranceArtwork: "assets/artwork/gate-panel.svg",
  entranceCrown: "assets/artwork/gate-crown.svg",
  venueArtwork: {
    src: "assets/artwork/evara-panorama.svg",
    type: "svg",
    alt: "An original illustration inspired by Evara's cream cottages, dark sloping roofs, terraced lawns, pool and green hills.",
    credit: "Original interpretation, not a photograph or an exact site plan.",
    source: "https://www.evararesort.com/",
    verifiedOn: "2026-09-26",
  },
  artworkUse: "user-supplied",
  illustrationSet: "supplied",
  artworkRights: { publicRedistributionConfirmed: true, confirmedOn: "2026-10-05" },
  illustrationNote: "The couple supplied the five celebration illustrations and confirmed permission to publish them. Haldi, Sangeet and Varmala retain their supplied settings; Baraat and Phere use original Evara-inspired settings. These are not portraits or confirmed event setups. Original creators retain their rights.",
  music: {
    src: "assets/music/iktara.mp3",
    title: "Iktara",
    credit: "Iktara, from Wake Up Sid (2009). User-supplied recording.",
    rights: "The couple confirmed permission to embed and redistribute this recording on their invitation website.",
    startSeconds: 25,
    startOnEntrance: true,
  },
  map: {
    url: "https://maps.app.goo.gl/TTHtMXssw3zdFs2S6",
    embedUrl: "https://www.google.com/maps?cid=1116871938007109148&output=embed",
    verifiedSource: "https://www.evararesort.com/location.html",
    verifiedOn: "2026-09-26",
  },
  // Supply a published docs.google.com/forms/... or forms.gle/... link. No form is sent or created here.
  rsvp: { googleFormUrl: "" },
  celebrations: [
    {
      id: "haldi", title: "Haldi", mood: "A little sunshine",
      date: "25 January 2027", time: "12:00 PM IST", start: "2027-01-25T12:00:00+05:30",
      description: "Join us for a little haldi, a lot of laughter, and a bright beginning to our celebrations.",
      artwork: { src: "assets/celebrations/haldi.png", type: "supplied", nativeSize: [736,1147], presentation: "original-composition", widthLimit: 1, heightLimit: 1, bottomInset: 0, alt: "The supplied ivory-and-yellow couple beneath a floral garden arch, with roses, bells and hanging flowers." },
    },
    {
      id: "sangeet", title: "Sangeet", mood: "Under a sky of lights",
      date: "25 January 2027", time: "7:00 PM IST", start: "2027-01-25T19:00:00+05:30",
      description: "An evening of favourite songs, happy feet and memories we'll be smiling about for years.",
      artwork: { src: "assets/celebrations/sangeet.png", type: "supplied", nativeSize: [736,1307], presentation: "original-composition", widthLimit: 1, heightLimit: 1, bottomInset: 0, alt: "The supplied purple-skirt and black-suit dance beneath chandeliers, lights and flowers, with disco balls and a misty stage." },
    },
    {
      id: "baraat", title: "Baraat", mood: "Make a little noise",
      date: "26 January 2027", time: "11:00 AM IST", start: "2027-01-26T11:00:00+05:30",
      description: "Come dance alongside us as the dhol plays and our families come together.",
      artwork: { src: "assets/celebrations/baraat.png", type: "supplied", nativeSize: [701,473], presentation: "layered", background: "assets/celebrations/baraat-setting.svg", widthLimit: .92, heightLimit: .73, bottomInset: .04, contacts: [[350.5,459.756,315.45,10]], alt: "The supplied Baraat procession with a groom on an ivory horse, dhol players, a walking guest and a parasol, in an original hill courtyard setting." },
    },
    {
      id: "varmala", title: "Varmala", mood: "A moment, just ours",
      date: "26 January 2027", time: "3:00 PM IST", start: "2027-01-26T15:00:00+05:30",
      description: "Two garlands, a room full of love, and the people who make this moment complete.",
      artwork: { src: "assets/celebrations/varmala.png", type: "supplied", nativeSize: [796,930], presentation: "original-composition", widthLimit: 1, heightLimit: 1, bottomInset: 0, alt: "The supplied couple beneath a pink floral mandap, with its original watercolor background retained." },
    },
    {
      id: "phere", title: "Phere", mood: "The heart of it all",
      date: "26 January 2027", time: "6:00 PM IST", start: "2027-01-26T18:00:00+05:30",
      description: "Be with us as we take our vows, with full hearts and your love around us.",
      artwork: { src: "assets/celebrations/phere.png", type: "supplied", nativeSize: [724,878], presentation: "layered", background: "assets/celebrations/phere-setting.svg", widthLimit: .82, heightLimit: .70, bottomInset: .065, contacts: [[65,619,51,6],[195,620,61,6],[517,685,141,8],[278,790,140,8]], glow: [278,701,191,140], fireOffset: [0,-75], alt: "The supplied walking couple and ceremony fire, moved closer together, beneath an original ivory-draped floral mandap with a stone platform, garden lamps and distant hills." },
    },
  ],
};

// Replace a film and its poster together. Keep sample labels until you have your own footage.
export const films = {
  branches: {
    src: "assets/media/branches-web.mp4",
    poster: "assets/media/branches-poster.jpg",
    caption: "In the green",
    description: "Foliage swaying in a soft breeze",
    hasAudio: false,
    label: "Sample footage / not the actual venue",
    credit: "franklandgrave / Mixkit",
    source: "https://mixkit.co/free-stock-video/branches-swaying-in-the-wind-95/",
    creatorUrl: "https://mixkit.co/@franklandgrave/",
    license: "Mixkit Stock Video Free License",
    licenseUrl: "https://mixkit.co/license/#videoFree",
    crop: "50% 50%",
  },
  flowers: {
    src: "assets/media/flowers-web.mp4",
    poster: "assets/media/flowers-poster.jpg",
    caption: "A little colour, a little breeze",
    description: "Pink bougainvillea against a blue sky",
    hasAudio: false,
    label: "Sample footage / not the actual venue",
    credit: "franklandgrave / Mixkit",
    source: "https://mixkit.co/free-stock-video/pink-flowers-wave-in-the-breeze-1168/",
    creatorUrl: "https://mixkit.co/@franklandgrave/",
    license: "Mixkit Stock Video Free License",
    licenseUrl: "https://mixkit.co/license/#videoFree",
    crop: "50% 64%",
  },
};
