export const invitation = {
  firstName: "Shubh",
  secondName: "Suchita",
  names: "Shubh & Suchita",
  invitation: "With our families by our side, we'd love to have you with us as we begin our forever.",
  dates: "25 & 26 January 2027",
  dateNumerals: "25 . 26 . 01 . 2027",
  venue: "Evara Spa & Resort",
  destination: "Jim Corbett, Uttarakhand, India",
  address: "Village Bhalon, Patkot, Uttarakhand 263159",
  venueUrl: "https://www.evararesort.com/",
  venueGalleryUrl: "https://www.evararesort.com/gallery.html",
  venueDescription: "Meet us among the green hills of Jim Corbett. We've saved two days for laughter, dancing, long conversations and the joy of having everyone together.",
  directionsUrl: "https://www.evararesort.com/location.html",
  calendarStart: "20270125",
  calendarEndExclusive: "20270127",
  calendarUid: "shubh-suchita-wedding-20270125",
  countdownTarget: "2027-01-25T12:00:00+05:30",
  scheduleNote: "All celebration times are in Indian Standard Time (IST).",
  guestNote: "Travel and stay details are forthcoming.",
  note: "As we get ready to say yes to a lifetime together, we're thinking of the people we want around us. You are one of them. Come share the happy chaos, the quiet moments and all the love these two days will hold. Having you there would mean so much to us.",
  closing: "It won't be the same without you.",
  artwork: "assets/artwork/couple-transparent.png",
  artworkAlt: "Shubh and Suchita's pink illustrated wedding artwork with florals, two dogs, a teacup and a city bridge.",
  entranceArtwork: "assets/artwork/gate-panel.svg",
  venueArtwork: {
    src: "assets/artwork/evara-panorama.svg",
    type: "svg",
    alt: "An original illustration inspired by Evara's cream cottages, dark sloping roofs, terraced lawns, pool and green hills.",
    credit: "Original interpretation, not a photograph or an exact site plan.",
    source: "https://www.evararesort.com/",
    verifiedOn: "2026-09-26",
  },
  illustrationNote: "Evara-inspired settings. Representative couple and imagined celebration decor.",
  music: {
    src: "assets/music/iktara.mp3",
    title: "Iktara",
    credit: "Iktara, from Wake Up Sid (2009). User-supplied recording.",
    rights: "The couple confirmed permission to embed and redistribute this recording on their invitation website.",
    startSeconds: 12,
    startOnEntrance: true,
  },
  map: {
    url: "https://maps.app.goo.gl/TTHtMXssw3zdFs2S6",
    embedUrl: "https://www.google.com/maps?cid=1116871938007109148&output=embed",
    verifiedSource: "https://www.evararesort.com/location.html",
    verifiedOn: "2026-09-26",
  },
  // Supply a published docs.google.com/forms/... or forms.gle/... link. No form is sent or created here.
  rsvp: { googleFormUrl: "" },
  celebrations: [
    {
      id: "haldi", title: "Haldi", mood: "A little sunshine",
      date: "25 January 2027", time: "12:00 PM IST", start: "2027-01-25T12:00:00+05:30",
      description: "Join us for a little haldi, a lot of laughter, and a bright beginning to our celebrations.",
      artwork: { src: "assets/scenes/haldi.svg", type: "svg", alt: "A representative couple seated among flowers, with bowls of haldi." },
    },
    {
      id: "sangeet", title: "Sangeet", mood: "Under a sky of lights",
      date: "25 January 2027", time: "7:00 PM IST", start: "2027-01-25T19:00:00+05:30",
      description: "An evening of favourite songs, happy feet and memories we'll be smiling about for years.",
      artwork: { src: "assets/scenes/sangeet.svg", type: "svg", alt: "The same representative couple dancing under festive lights, in evening outfits." },
    },
    {
      id: "baraat", title: "Baraat", mood: "Make a little noise",
      date: "26 January 2027", time: "11:00 AM IST", start: "2027-01-26T11:00:00+05:30",
      description: "Come dance alongside us as the dhol plays and our families come together.",
      artwork: { src: "assets/scenes/baraat.svg", type: "svg", alt: "The representative groom arriving on foot among dancing guests and dhol players." },
    },
    {
      id: "varmala", title: "Varmala", mood: "A moment, just ours",
      date: "26 January 2027", time: "3:00 PM IST", start: "2027-01-26T15:00:00+05:30",
      description: "Two garlands, a room full of love, and the people who make this moment complete.",
      artwork: { src: "assets/scenes/varmala.svg", type: "svg", alt: "The representative couple exchanging floral garlands in a garden inspired by Evara's cottages and green hills." },
      sceneryNote: "Venue-inspired artwork. Decor and ceremony locations are illustrative.",
    },
    {
      id: "phere", title: "Phere", mood: "The heart of it all",
      date: "26 January 2027", time: "6:00 PM IST", start: "2027-01-26T18:00:00+05:30",
      description: "Be with us as we take our vows, with full hearts and your love around us.",
      artwork: { src: "assets/scenes/phere.svg", type: "svg", alt: "The representative couple taking gentle steps around a sacred fire beneath a floral mandap." },
    },
  ],
};

// Replace a film and its poster together. Keep sample labels until you have your own footage.
export const films = {
  branches: {
    src: "assets/media/branches-web.mp4",
    poster: "assets/media/branches-poster.jpg",
    caption: "In the green",
    description: "Foliage swaying in a soft breeze",
    hasAudio: false,
    label: "Sample footage / not the actual venue",
    credit: "franklandgrave / Mixkit",
    source: "https://mixkit.co/free-stock-video/branches-swaying-in-the-wind-95/",
    creatorUrl: "https://mixkit.co/@franklandgrave/",
    license: "Mixkit Stock Video Free License",
    licenseUrl: "https://mixkit.co/license/#videoFree",
    crop: "50% 50%",
  },
  flowers: {
    src: "assets/media/flowers-web.mp4",
    poster: "assets/media/flowers-poster.jpg",
    caption: "A little colour, a little breeze",
    description: "Pink bougainvillea against a blue sky",
    hasAudio: false,
    label: "Sample footage / not the actual venue",
    credit: "franklandgrave / Mixkit",
    source: "https://mixkit.co/free-stock-video/pink-flowers-wave-in-the-breeze-1168/",
    creatorUrl: "https://mixkit.co/@franklandgrave/",
    license: "Mixkit Stock Video Free License",
    licenseUrl: "https://mixkit.co/license/#videoFree",
    crop: "50% 64%",
  },
};
